# -------------------------------------------
# GitHub Actions Part: Test-1
# 
# Copyleft (c) by Alexander Sibagatov 2020.
# -------------------------------------------
name: My-GitHub-Actions
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy--ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing job"
      
    - name: Execure few commands
      run: |
        echo "Hello message1"
        echo "Hello message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run: ls -lah
    
    - name: Git clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder
      run: ls -lah
        

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is job level Variable1"
      VAR2: "This is job level Variable2"
    
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello World from Deploy job"
    
    - name: Print env vars
      run: | 
        echo "VAR1: ${{ env.VAR1 }}"
        echo "VAR2: ${{ env.VAR2 }}"
        echo "VAR3: $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is super lockal environment variable"
    
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
    
    - name: Lets test some pakages if they are here 1
      run: aws --version
    
    - name: Lets test some pakages if they are here 2
      run: zip --version
